### GENERAL SETTINGS ###

# Site settings
title: HydPy
description: "Community driven group for promoting python in Hyderabad."
analytics: UA-25759569-4 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""
future: true

# gems setting to generate sitemap
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is


# Making projects separate from posts
collections:
  faqs:
    output: true

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/HydPy/
  - title: meetup
    url: https://www.meetup.com/HydPyGroup/
  - title: facebook
    url: https://www.facebook.com/HydPy/
  - title: x-twitter
    url: https://www.x.com/HydPython/
  - title: telegram
    url: https://t.me/HydPy
  - title: linkedin
    url: https://www.linkedin.com/company/hydpy/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: hydpy@python.org
email-list: https://mail.python.org/mm3/mailman3/lists/hydpy.python.org/

# Clients information. Shown on Home and About pages.
pygroups:
  - name: Python Software Foundation
    img: psf.png
    url: https://www.python.org/psf/
  - name: PyDelhi
    img: pydelhi.png
    url: https://pydelhi.org
  - name: PythonPune
    img: PythonPune_banner.svg
    url: https://pythonpune.in/
  - name: Chennaipy
    img: chennaipy.png
    url: https://www.chennaipy.org

sponsors:
  - name: Zulip
    img: zulip.png
    url: https://zulipchat.com

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hyderabad Python User group is growing and active Python user community in Hyderabad. We believe in 'Come for the Language, Stay for the Community!'"

# Testimonial content. Shown on Home and About page.
testimonial:
  message: "Python is an experiment in how much freedom programmers need. Too much freedom and nobody can read another's code; too little and expressiveness endangered."
  author: Guido van Rossum
  position: Creator of Python
