### GENERAL SETTINGS ###

# Site settings
title: HydPy
description: "Community driven group for promoting python in Hyderabad."
analytics: UA-25759569-4 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# gems setting to generate sitemap
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#356ea1" #"#F70031"
  primary_rgb: "0,115,200" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  faqs:
    output: true

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/HydPy/
  - title: meetup
    url: https://www.meetup.com/Hyderabad-Python-Meetup-Group/
  - title: facebook
    url: https://www.facebook.com/HydPy/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: hydpy@python.org
email-list: https://mail.python.org/mm3/mailman3/lists/hydpy.python.org/


# Clients information. Shown on Home and About pages.
pygroups:
  - name: pssi
    img: pssi_logo.png
    url: https://pssi.org.in
  - name: pydelhi
    img:
    url: https://pydelhi.org
  - name: PythonPune
    img:
    url: http://pune.python.org.in
  - name: Chennaipy
    img: chennaipy.png
    url: http://www.chennaipy.org

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hyderabad Python User group is growing and active Python user community in Hyderabad. We believe in 'Knowledge is power, community is strength'!!!"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Python is an experiment in how much freedom programmers need. Too much freedom and nobody can read another's code; too little and expressiveness endangered."
    author: Guido van Rossum
    position: Creator of Python
